# Generated by Django 3.1.1 on 2021-07-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmname', models.CharField(max_length=50)),
                ('SizeOfFarm', models.IntegerField()),
                ('address', models.TextField(default='')),
                ('area', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_owner', to='accounts.farmuser')),
            ],
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_image', to='farmuser.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmAvailble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmprice', models.IntegerField()),
                ('available', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='farmuser.farm')),
            ],
        ),
    ]
