# Generated by Django 3.1.1 on 2021-07-28 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farmuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmname', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('SizeOfFarm', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='\u202aseee.jpg', null=True, upload_to='farms')),
                ('address', models.TextField(default='')),
                ('area', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FarmAvailble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmprice', models.IntegerField()),
                ('available', models.DateField(validators=[farmuser.models.validate_date])),
                ('is_booked', models.BooleanField(default=False)),
                ('booking_order_id', models.CharField(default='', max_length=100, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='farmuser.farm')),
            ],
            options={
                'unique_together': {('farm', 'available')},
            },
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='\u202aseee.jpg', null=True, upload_to='farms/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_image', to='farmuser.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('farm_booking_date', models.DateField(validators=[farmuser.models.validate_date])),
                ('price', models.IntegerField()),
                ('booking_order_id', models.CharField(default='', max_length=100, null=True)),
                ('No_of_People', models.IntegerField(default=1)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_booking', to='farmuser.farm')),
                ('farmavailable', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_available', to='farmuser.farmavailble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
