# Generated by Django 3.1.1 on 2021-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmimage',
            name='images',
            field=models.FileField(upload_to='farm/'),
        ),
    ]
