# Generated by Django 3.1.1 on 2021-07-04 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmuser', '0002_auto_20210704_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
