# Generated by Django 3.1.1 on 2021-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0003_auto_20210704_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
