# Generated by Django 3.1.1 on 2021-07-04 18:47

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmuser', '0004_auto_20210704_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('farm_booking_date', models.DateField()),
                ('price', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name=range(0, 50000))),
                ('No_of_People', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name=range(1, 20))),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_booking', to='farmuser.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
