# Generated by Django 3.1.1 on 2021-07-04 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0005_farmbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmbooking',
            name='No_of_People',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='farmbooking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
