# Generated by Django 3.1.1 on 2021-07-10 20:22

from django.db import migrations, models
import farmuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0006_auto_20210705_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmavailble',
            name='available',
            field=models.DateField(validators=[farmuser.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='farmbooking',
            name='farm_booking_date',
            field=models.DateField(validators=[farmuser.models.validate_date]),
        ),
        migrations.AlterUniqueTogether(
            name='farmavailble',
            unique_together={('farm', 'available')},
        ),
    ]
