# Generated by Django 3.1.1 on 2021-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0008_farmavailble_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmimage',
            name='images',
            field=models.ImageField(upload_to='farm/'),
        ),
    ]
