# Generated by Django 3.1.1 on 2021-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0009_auto_20210712_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmimage',
            name='images',
            field=models.FileField(upload_to='farm/'),
        ),
    ]
