# Generated by Django 3.1.1 on 2021-07-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0010_auto_20210712_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmimage',
            name='images',
        ),
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, default='\u202aseee.jpg', null=True, upload_to='farms'),
        ),
        migrations.AddField(
            model_name='farmimage',
            name='image',
            field=models.FileField(blank=True, default='\u202aseee.jpg', null=True, upload_to='farms/'),
        ),
    ]
