# Generated by Django 3.1.1 on 2021-07-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0011_auto_20210712_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmbooking',
            name='farmavailable',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_available', to='farmuser.farmavailble'),
        ),
    ]
