# Generated by Django 3.1.1 on 2021-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0012_farmbooking_farmavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmavailble',
            name='booking_order_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmbooking',
            name='booking_order_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
