# Generated by Django 3.1.1 on 2021-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0013_farmavailble_booking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmbooking',
            name='booking_order_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
