# Generated by Django 3.1.1 on 2021-07-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmuser', '0013_auto_20210725_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('-id',)},
        ),
    ]
