# Generated by Django 3.1.1 on 2021-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmuser',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
